[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"

[rpc_endpoints]
base-sepolia = "https://sepolia.base.org"
base = "https://mainnet.base.org"

[etherscan]
base-sepolia = { key = "${BASESCAN_API_KEY}" }
